# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleVote', '0002_remove_candidate_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Date Cast'),
        ),
    ]
