# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='ballotitem',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellation_vote.Ballot'),
        ),
        migrations.AddField(
            model_name='ballotitem',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellation_vote.PollOption'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='selected_options',
            field=models.ManyToManyField(through='constellation_vote.BallotItem', to='constellation_vote.PollOption'),
        ),
        migrations.AlterUniqueTogether(
            name='ballotitem',
            unique_together=set([('ballot', 'order'), ('ballot', 'poll_option')]),
        ),
    ]
