# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': (('poll_owned_by', 'Poll Owner'), ('poll_visible', 'Poll is Visible'))},
        ),
    ]
