# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='starts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
