# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0002_auto_20170330_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': (('poll_owned_by', 'Poll Owner'), ('poll_visible_to', 'Poll is Visible'))},
        ),
    ]
