# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0002_many2many'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballotitem',
            options={'ordering': ['order']},
        ),
    ]
