# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0004_auto_20170415_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='cast_once',
            new_name='cast_multiple',
        ),
        migrations.AddField(
            model_name='poll',
            name='ip_range',
            field=models.CharField(default='0.0.0.0/0', max_length=18),
        ),
    ]
