# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0004_auto_20170404_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
