# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0005_auto_20170416_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='date_cast',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
