# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0006_ballot_date_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='ip_range',
            field=models.TextField(default='0.0.0.0/0'),
        ),
    ]
